# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraftTargetVersion = 1.21.1
minecraftVersion = 1.21.1
yarnMappings = 1.21.1+build.3
loaderVersion = 0.18.2

kotlin.code.style = official
systemProp.kotlinVersion = 2.4.0
fabricKotlinVersion = 1.13.12+kotlin.2.4.0

# Mod Properties
modVersion = 1.19.3
mavenGroup = io.sc3

# Dependencies
# check this on https://fabricmc.net/develop/
fabricVersion = 0.116.9+1.21.1

ccVersion = 1.120.2
ccMcVersion = 1.21.1
ccTargetVersion = >=1.120.2

clothConfigVersion = 15.0.140
clothApiVersion = 4.0.65
modMenuVersion = 11.0.3

configurateVersion = 4.1.2

trinketsVersion = 3.10.0
cardinalComponentsVersion = 6.1.0

scLibraryVersion = 1.10.5

# ===========================
# Third party mod integration
# ===========================
scPeripheralsVersion = 1.10.5
scGoodiesVersion = 1.14.0
figuraVersion = 0.1.5+1.21.1
common_protection_version = 1.0.0
ledger_version = 1.2.10+local
emi_version = 1.1.24+1.21.1
